all:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8 Frequencer.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8 TestCase.java -classpath "../.."
run:
	java -classpath "../.." s4.B233382/Hello
	java -classpath "../.." s4.B233382/Frequencer
	java -classpath "../.." s4.B233382/InformationEstimator
	java -ea -classpath "../.." s4.B233382/TestCase
clean:
	rm -f *.class *~


