all:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8 Frequencer.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8 TestCase.java -classpath "../.."
run:
	java -classpath "../.." s4.T000002/Hello
	java -classpath "../.." s4.T000002/Frequencer
	java -classpath "../.." s4.T000002/InformationEstimator
	java -ea -classpath "../.." s4.T000002/TestCase
clean:
	rm -f *.class *~


