all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.umemura/Hello
	java -classpath "../.." s4.umemura/Frequencer
#	java -classpath "../.." s4.umemura/InformationEstimator
#	java -classpath "../.." s4.umemura/TestCase
