all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.slow/Hello
#	java -classpath "../.." s4.slow/Frequencer
#	java -classpath "../.." s4.slow/InformationEstimator
	java -classpath "../.." s4.slow/TestCase
